spring:
    application:
        name: message

    data:
        mongodb:
            uri: mongodb://raven:raven@mongodb_raven:27018/raven?authSource=admin

    kafka:
        bootstrap-servers: kafka:9092
        consumer:
            group-id: chat-consumers
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
    level:
        root: WARN
        org.apache.kafka: WARN
        org.springframework.kafka: WARN